name: $(Date:yy.M)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Use Python 3.8'

- script: |
    echo '$(Build.BuildNumber)' > teslacam/VERSION
  displayName: 'Write version number'

- script: |
    python -m pip install wheel
    python setup.py sdist bdist_wheel
  displayName: 'Build wheel'

- task: TwineAuthenticate@1
  inputs:
    pythonUploadServiceConnection: 'PyPI production'
  displayName: 'Authenticate to PyPI'

- script: |
    python -m pip install twine
    python -m twine upload -r pypi --config-file $(PYPIRC_PATH) dist/*
  displayName: 'Upload to PyPI'